support Spectrum1D reading from file with flux in counts
astropy/specutils pull request #1018
Opened 2023-02-21 20:54 UTC by kecnry

this PR implements an exception to support reading a Spectrum1D from a file with fluxes in counts.  This does not however address more general reading round-tripping such as the one reported in #997.  Note also that this is just hardcoding an additional exception, `Spectrum1D` currently doesn't seem to do any unit checking on the inputs for flux, and so other units might result in the same error (including non-sensical units, like fluxes with units of meters).

Example (that used to raise an `OSError: Could not identify column containing the flux`):

```
import specutils
import numpy as np
import astropy.units as u

sp = specutils.Spectrum1D(flux=np.linspace(0,1,11)*u.Unit('count'), spectral_axis=np.random.random(11)*u.Unit('J'))
sp.write("spec.fits", overwrite=True)

specutils.Spectrum1D.read("spec.fits")
```

2023-02-21 21:17 UTC, pllim commented
> u.Unit('J')

You sure you didn't mean Jy?

2023-02-21 21:17 UTC, pllim commented
Are we able to turn that example you provided into a test?

2023-02-21 21:23 UTC, kecnry commented
> You sure you didn't mean Jy?

No, this is for spectral axis, not flux, so I just chose a random compatible unit for the spectral axis.  Swap out with Hz or um if you'd rather!

> Are we able to turn that example you provided into a test?

Sure, we could provide a regression test for this same hardcoded case, but it really would only test that someone doesn't revert this commit... so I'm wondering if it makes more sense to write general tests with the longer-term solution?  Happy to basically copy-paste this in to a test though just to make sure it doesn't raise errors.

2023-02-21 21:42 UTC, pllim commented
> No, this is for spectral axis, not flux

Doh! Ignore me... 😆 

> but it really would only test that someone doesn't revert this commit

Right, we wouldn't want regression, which could happen if we ever refactor the internals.

2023-02-22 18:15 UTC, pllim reviewed
I think the test could be written using `parametrize` and there is no need for random number generator. Please see suggestions.

Not sure what's up with the change log, maybe @rosteen only updates it on release? https://github.com/astropy/specutils/blob/main/CHANGES.rst

2023-02-22 18:15 UTC, pllim commented on specutils/tests/test_spectrum1d.py
> +def test_flux_unit_io_roundtrip(tmpdir):
```suggestion
def test_flux_unit_io_roundtrip(tmp_path):
```

2023-02-22 18:15 UTC, pllim commented on specutils/tests/test_spectrum1d.py
> +    fname = str(tmpdir.join('flux_unit_io_roundtrip.fits'))
```suggestion
    fname = str(tmp_path / 'flux_unit_io_roundtrip.fits')
```

2023-02-22 18:15 UTC, pllim commented on specutils/tests/test_spectrum1d.py
> +def test_flux_unit_io_roundtrip(tmpdir):
```suggestion
@pytest.mark.parametrize("flux_unit", ["adu", "ct/s", "count"])
def test_flux_unit_io_roundtrip(tmpdir, flux_unit):
```

2023-02-22 18:15 UTC, pllim commented on specutils/tests/test_spectrum1d.py
> +        assert sp_load.flux.unit == sp.unit
```suggestion
    sp = Spectrum1D(flux=np.ones(11) * u.Unit(flux_unit),
                    spectral_axis=np.arange(1, 12) * u.Unit('Hz'))
    sp.write(fname, overwrite=True)

    sp_load = Spectrum1D.read(fname)
    assert sp_load.flux.unit == sp.flux.unit
```

2023-02-22 22:00 UTC, rosteen commented
> Not sure what's up with the change log, maybe @rosteen only updates it on release? https://github.com/astropy/specutils/blob/main/CHANGES.rst

Yeah, I've been updating it when I do a release. I'm certainly not opposed to people updating it when they make a PR though!

I'm going to approve this, but generally agree with your suggestions @pllim . I'm about to log off for vacation but feel free to merge this once those are addressed.

2023-02-22 22:01 UTC, rosteen approved these changes

2023-02-23 01:25 UTC, dhomeier requested changes
I agree with the requested changes, otherwise this looks sensible. Yes, `Spectrum1D.__init__` does not make any checks on flux `PhysicalType`, but there you are directly passing your quantity. `parsing_utils` are searching for some compatible data fields in an input file, so it makes sense to be more conservative.

2023-02-23 14:35 UTC, pllim commented
@dhomeier , does the PR look okay to you now, or is there something else? Thanks!

2023-02-23 14:52 UTC, dhomeier approved these changes

2023-02-23 14:53 UTC, dhomeier commented
Everything you had requested as far as I can see; good to me too, thanks!

2023-02-23 14:54 UTC, merged

2023-02-23 14:54 UTC, pllim commented
Thanks, all!