Add github actions copied from astropy
astropy/specutils pull request #736
Opened 2020-11-26 00:13 UTC by aragilar

This I think should close #733. Feel free to edit this as needed (I'm not that familiar with github actions, I've mainly used other CI services, so feel free to completely rewrite/rebase this branch - I'm posting this so that specutils will have a CI running).

2020-11-30 16:14 UTC, pllim commented
Thank you! Since this is the initial implementation from a fork, it would only run on your fork but given how things are currently set up, it is not running. So you might have to push a temporary commit to let it run from your fork to prove that this works.

https://github.com/aragilar/specutils/actions

2020-11-30 16:24 UTC, mwcraig commented
THis looks pretty good. A few questions:

+ Does `specutils` need the 32-bit and parallel tests?
+ I don't think the label action will work unless you created a secret for this repository. 

OTher than that it looks good, but let's see what happens in the actions on your fork.

2020-11-30 16:25 UTC, mwcraig commented on .github/workflows/ci_workflows.yml
> +    - master
Drop this for now to make the actions run on your fork. 

```suggestion
```

2020-11-30 21:12 UTC, eteq requested changes
Thanks for this @aragilar ! A few things I noticed that need updating to be consistent with what `travis` was doing:


* We need a build that tests against the latest astropy LTS (not in astropy itself, of course, since it *is* the LTS).  This alread exists in `tox`, it just needs a matrix element.  `py36-test-astropylts-numpy116` is the toxenv you want - you can just add that to the matrix as another item
* There isn't a separate doc build right now, so  this should also get a `build_docs` in the matrix
* Since it's all subsumed, this PR should delete the `.travis.yml` too (yay!)
* I agree there's no need for the 32 bit/parallel runs, so can probably just delete that one.
* (one other thing that was easy to express as an inline suggestion)

2020-11-30 21:12 UTC, eteq commented on .github/workflows/ci_workflows.yml
> +            toxenv: py37-test-devdeps
This is what it is in the latest travis.yml - I'm not sure if there's a reason for that or not, but probably best to stay consistent.
```suggestion
            python: 3.8
            toxenv: py38-test-devdeps
```

2020-11-30 21:12 UTC, eteq commented on .github/workflows/ci_cron_weekly.yml
> +            toxenv: py37-test-devdeps
(as above)
```suggestion
            python: 3.8
            toxenv: py38-test-devdeps
```

2020-11-30 21:16 UTC, eteq commented
Oh and an *alternative* to my suggestion above is to get the readthedocs build set up like `astropy`, but I think it's probably better to do it in actions as a later step since it requires fiddling around with RTD settings (which I think requires admin rights right now).

2020-11-30 21:25 UTC, pllim commented
Re: RTD -- Yes, it is only one-click to enable PR build there but you do need to be admin there. Looking at https://readthedocs.org/projects/specutils/ , the following people can enable it:

* @keflavich 
* @nmearl 
* Whoever has the keys to `astropy` RTD account
* Whoever has the keys to `specutils` RTD account

2020-12-01 00:18 UTC, aragilar commented
I've added the inline suggestions, which looks like it's caused actions to run for the commit - https://github.com/aragilar/specutils/actions/runs/392730140. I'll have a go at the other changes, but feel free to push changes, rather than waiting for me to make them.

2020-12-01 15:29 UTC, eteq commented
> Re: RTD -- Yes, it is only one-click to enable PR build there but you do need to be admin there. 

I didn't realize it was this easy!  I just turned it on right now. So lets give that a try - I'm a bit worried about some of the quirks of the `specutils` docs getting in the way here, but we should just try it and see since the RTD approach is closer to what the user sees in the end anyway.

So @aragilar - never mind about my suggestion to add  `build_docs` to the matrix.

2020-12-01 15:35 UTC, pllim commented
> I'm a bit worried about some of the quirks

In your `.readthedocs.yml`, you can set it to allow warnings if you worry about warnings failing the RTD PR build. But then again, once you ignore warnings, they tend to multiply like rabbits and opens up a rabbit hole. So, ignore at your own risk.

Hope this helps!

2020-12-01 16:41 UTC, mwcraig commented on .github/workflows/ci_workflows.yml
> +            python: 3.7
```suggestion
            python: 3.6
```

(I'm not a maintainer so I can't push to your branch)

2020-12-01 20:56 UTC, eteq commented on .github/workflows/ci_workflows.yml
> +      run: sudo apt-get install language-pack-de tzdata
```suggestion
      run: sudo apt-get install language-pack-de tzdata graphviz
```
I think this is what's necessary to get the doc build to run...

2020-12-01 22:00 UTC, eteq commented
Huzzah!  https://github.com/aragilar/specutils/runs/1482516182 looks like it all working except for the "allowed failure" (which I'm not sure we actually want anyway in the PRs vs the weeklies, but we can address that in a follow-on PR.

2020-12-01 22:00 UTC, eteq approved these changes

2020-12-01 22:02 UTC, eteq commented
I think this is probably ready now, but I'm just going to give a bit of time in case @nmearl wants to jump in (as the originator of the most recent iteration of the `.travis.yml`)

2020-12-07 19:25 UTC, nmearl approved these changes
This looks good to me. Although, it seems we might need to add another matrix entry in the future to include the external packages tox environment that includes the JWST pipeline to test the IO, but that might be fine as a follow-up.

2020-12-14 20:02 UTC, pllim commented
CI passed. Any reason why this is not yet merged? Thanks!

2020-12-17 15:17 UTC, javerbukh commented
Pinging @eteq and @nmearl to merge if everything looks good

2020-12-17 15:36 UTC, merged

2020-12-17 15:37 UTC, eteq commented
@pllim - the reason was that I was waiting for @nmearl... and missed that he approved it!  So merged just now.