Add spectral_slab function.
astropy/specutils pull request #753
Opened 2021-01-05 16:27 UTC by ibusko

As per issue #744

2021-01-07 21:58 UTC, rosteen requested changes
The spectral-cube slab functions takes upper and lower spectral bounds as input rather than a region (see https://spectral-cube.readthedocs.io/en/latest/manipulating.html#extracting-a-spectral-slab), so to preserve back-compatibility I think this should take the bounds as input and construct the region internally.

2021-01-15 14:31 UTC, rosteen commented on specutils/manipulation/extract_spectral_region.py
> +    transition from `spectral-cube`.
It looks like this line is causing the tests to fail, with the quotes the docs are expecting `spectral-cube` to reference an object defined in this file (I think).
```suggestion
    transition from the spectral-cube package.
```

2021-01-20 16:13 UTC, rosteen approved these changes
Looks good to me. I noticed in comparing the output to that of the spectral-cube version that the upper bound is handled slightly differently. With an upper bound of 4000 A on my test cube, spectral-cube's version of spectral_slab generated output with a last spectral axis value of 4000.37, whereas this version has the last spectral axis value as 3999.45. I think this version makes more sense (and is consistent with other behavior in specutils) and I'm approving, but whoever writes the docs for #761 should be sure to note the difference.

2021-01-20 19:30 UTC, javerbukh approved these changes
This looks good, although I would suggest a final review from a scientist to make sure this is the expected workflow.

2021-01-20 21:13 UTC, nmearl requested changes
Minor comments, but looks good. The SDSS servers are currently down, which is impacting the builds. I'll let this sit for a bit and see if they come back up, but otherwise it *looks* like local tests are passing for me.

2021-01-20 21:13 UTC, nmearl commented on specutils/manipulation/extract_spectral_region.py
> +        from the original spectrum.
```suggestion
    lower, upper: `~astropy.units.Quantity`
        The lower and upper bounds of the region to extract 
        from the original spectrum.
```

2021-01-20 21:13 UTC, nmearl commented on specutils/manipulation/extract_spectral_region.py
> +def spectral_slab(spectrum, s1, s2):
```suggestion
def spectral_slab(spectrum, lower, upper):
```

For consistency with other bounds-related functionality in specutils (e.g. `SpectralRegion`), we should reference the range using similar verbiage.

2021-01-20 21:13 UTC, nmearl commented on specutils/manipulation/extract_spectral_region.py
> +    region = SpectralRegion(s1, s2)
```suggestion
    region = SpectralRegion(lower, upper)
```

2021-01-25 19:17 UTC, PatrickOgle approved these changes
Looks good.  I tested spectral_slab on a manga cube, and it returned the correct wavelength subset of the spec1d object. I didn't test edge case of wavelength bin equal to slab start/end wavelengths.

2021-01-29 18:03 UTC, eteq commented
LGTM too, so merging!  w.r.t. the SDSS servers, I think we need to update all the examples because the current URL is not very stable.  I thought I wrote an issue on this but can't find it right now - will try to make one later today.

2021-01-29 18:03 UTC, merged