Document new spectral cube-related functionality in specutils
astropy/specutils pull request #776
Opened 2021-02-03 20:44 UTC by ibusko

2021-02-04 16:17 UTC, PatrickOgle commented
I don't see the spectral_slab doc in Files changed for this PR, so I can't complete the requested review.

2021-02-04 16:36 UTC, ibusko commented
@PatrickOgle I can see it 
<img width="1152" alt="image" src="https://user-images.githubusercontent.com/3577145/106924607-38b31c80-66dd-11eb-8889-09182c27eb80.png">

2021-02-06 19:30 UTC, nmearl requested changes

2021-02-06 19:30 UTC, nmearl commented on docs/analysis.rst
> +--------
```suggestion
------
```

2021-02-06 19:30 UTC, nmearl commented on docs/spectral_regions.rst
> +in between disjoint spectral regions, can be extracted with
```suggestion
in between disjointed spectral regions, can be extracted with
```

2021-02-10 17:49 UTC, PatrickOgle approved these changes
Documentation on new functionality looks good.

2021-02-12 14:01 UTC, rosteen commented
The doc build failure is:

```
Warning, treated as error:
/home/runner/work/specutils/specutils/docs/spectral_regions.rst:213:py:obj reference target not found: extract_bounding_spectral_region
```

Maybe it needs the full package reference `specutils.manipulation.extract_bounding_spectral_region` there instead of just the function name?

2021-02-12 16:28 UTC, closed without merging

2021-02-12 16:31 UTC, ibusko commented
This is superseded by #783